# Parker Jackman
# Assn 4 task 1
# Snowman

import turtle
turtle.showturtle()
turtle.width(2)
turtle.speed(10)
turtle.color("black")
turtle.fillcolor("white")

turtle.penup()
turtle.goto(0, -245)
turtle.pendown()
turtle.begin_fill()
turtle.circle(90)

turtle.penup()
turtle.goto(0,-70)
turtle.pendown()
turtle.circle(70)


turtle.penup()
turtle.goto(0, 65)
turtle.pendown()
turtle.circle(50)

turtle.penup()
turtle.goto(-15, 120)
turtle.pendown()
turtle.fillcolor("black")
turtle.begin_fill()
turtle.circle(7)

turtle.penup()
turtle.goto(15, 120)
turtle.pendown()
turtle.circle(7)
turtle.end_fill()

turtle.penup()
turtle.goto(-21, 100)
turtle.pendown()
turtle.right(45)
turtle.circle(30, 90)


turtle.penup()
turtle.goto(-50, 160)
turtle.pendown()
turtle.right(45)
turtle.color("green")
turtle.fillcolor("green")
turtle.begin_fill()

turtle.forward(100)
turtle.left(90)
turtle.forward(20)
turtle.left(90)
turtle.forward(20)
turtle.right(90)
turtle.forward(60)
turtle.left(90)
turtle.forward(60)
turtle.left(90)
turtle.forward(60)
turtle.right(90)
turtle.forward(20)
turtle.left(90)
turtle.forward(20)
turtle.end_fill()

turtle.penup()
turtle.goto(60, 35)
turtle.pendown()
turtle.color("brown")
turtle.left(125)
turtle.forward(100)
turtle.right(180)
turtle.forward(25)
turtle.right(145)
turtle.forward(25)
turtle.right(180)
turtle.forward(25)
turtle.left(85)
turtle.forward(25)

turtle.penup()
turtle.goto(-60, 35)
turtle.pendown()
turtle.left(180)
turtle.forward(100)
turtle.right(180)
turtle.forward(25)
turtle.left(145)
turtle.forward(25)
turtle.right(180)
turtle.forward(25)
turtle.right(100)
turtle.forward(25)

turtle.penup()
turtle.goto(0, 30)
turtle.pendown()
turtle.left(160)
turtle.color("black")
turtle.fillcolor("black")
turtle.begin_fill()
turtle.circle(7)

turtle.penup()
turtle.goto(0, -7)
turtle.pendown()
turtle.circle(7)

turtle.penup()
turtle.goto(0,-44)
turtle.pendown()
turtle.circle(7)
turtle.end_fill()

turtle.penup()
turtle.goto(200, -30)

turtle.done()